name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clona repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura acesso SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ec2-18-212-108-204.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      # Realiza deploy no servidor EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@ip-172-31-36-10 "
            cd /opt/web-server/personal-portfolio &&
            git pull origin main &&
            sudo systemctl restart nginx
          "
